steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    id: Update kafka master
    entrypoint: /bin/sh
    args:
      - '-c'
      - |
        gcloud compute --project "kafka-408805" ssh --zone "australia-southeast1-b" "instance-1" --command='/bin/sh /home/phamthiminhtu/pull.sh'
