steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    id: Update kafka master
    entrypoint: /bin/sh
    args:
      - '-c'
      - |
        mkdir -p ~/root/.ssh && \
        gcloud secrets versions access latest --secret=cloud-build-ssh-key > ~/root/.ssh/id_rsa && \
        chmod 600 ~/root/.ssh/id_rsa && \
        gcloud secrets versions access latest --secret=cloud-build-ssh-key-pub > ~/root/.ssh/id_rsa.pub && \
        chmod 600 ~/root/.ssh/id_rsa.pub && \
        gcloud compute ssh instance-1 --project=kafka-408805 --zone=australia-southeast1-b --ssh-key-file=~/root/.ssh/id_rsa --troubleshoot && \
        gcloud compute ssh instance-1 --project=kafka-408805 --zone=australia-southeast1-b --ssh-key-file=~/root/.ssh/id_rsa --troubleshoot --tunnel-through-iap && \
        set -x && \
          gcloud compute ssh instance-1 --ssh-key-file=~/root/.ssh/id_rsa --zone=australia-southeast1-b --tunnel-through-iap  --command='/bin/sh /home/phamthiminhtu/pull.sh'
