steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    id: Update kafka master
    entrypoint: /bin/sh
    args:
      - '-c'
      - gcloud config set project kafka-408805
      - gcloud compute ssh instance-1	--zone australia-southeast1-b --command='/bin/sh /home/phamthiminhtu/pull.sh'
