steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    id: Update kafka master
    entrypoint: /bin/sh
    args:
      - '-c'
      - |
        mkdir -p ~/root/.ssh && \
        gcloud secrets versions access latest --secret=cloud-build-ssh-key > ~/root/.ssh/id_ed25519 && \
        chmod 600 ~/root/.ssh/id_ed25519 && \
        gcloud secrets versions access latest --secret=cloud-build-ssh-key-pub > ~/root/.ssh/id_ed25519.pub && \
        chmod 600 ~/root/.ssh/id_ed25519.pub && \
        cat ~/root/.ssh/id_ed25519.pub && \
        set -x && \
          gcloud compute ssh instance-1 --ssh-key-file=~/root/.ssh/id_ed25519 --zone=australia-southeast1-b --command='/bin/sh /home/phamthminhtu/kafka/pull.sh'
