steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    id: Update kafka master
    entrypoint: /bin/sh
    args:
      - '-c'
      - gcloud compute ssh cloud-build-ssh-key@35.197.169.207 instance-1 --zone=australia-southeast1-b --tunnel-through-iap  --command='/bin/sh /home/phamthminhtu/pull.sh'
